[package]
name = "dwmstatus-rs"
version = "0.1.0"
authors = ["stuart nelson <stuartnelson3@gmail.com>"]

[dependencies]
xcb = "^0.8"
libc = "^0.2"
chrono = "^0.4"
alsa = "^0.3.0"
network-manager = "^0.11"
crossbeam-channel = "^0.3"
