[package]
name = "dwmstatus-rs"
version = "0.1.0"
authors = ["stuart nelson <stuartnelson3@gmail.com>"]

[dependencies]
xcb = "^0.8.1"
libc = "^0.2.3"
chrono = "0.4"
alsa = "^0.2.0"
network-manager = "^0.8.6"
